version: '3'
services:
  mailhog:
    image: "mailhog/mailhog"
    ports:
     - "1025:1025"
     - "8025:8025"
    environment:
     - MH_STORAGE=maildir
     - MH_MAILDIR_PATH=/home/mailhog/fakesmtp
